#!/usr/bin/env python


"""
This is an _very_ simplified script that creates a custom formatted log file from the 
firewall.log file thats generated by the iptables rule set on Bifrozt. The new log file
thats generated can be used to visualize the outbound traffic if given to Logstalgia. 
"""


"""
Copyright (c) 2014, Are Hansen - Honeypot Development,

All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are
permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list
of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this
list of conditions and the following disclaimer in the documentation and/or other
materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND AN
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""


#   DEV NOTES
#
#   - 20141018: Upper limit for Logstalgia lines per second capabillities.
#   Logstalgia does does not handle massive amounts of traffic very well. When Bifrozt
#   blocks an outbound DDoS attack it can generate 80.0000 log entries per second in
#   average.
#   WORKAROUND: When parsing firewall.log, check for the number of entries per second.
#   If entries per second exceeds 700, ignore the preceeding lines containing the same
#   time stamp per second.
#
#   - 20141126: Replace non-rfc1918 addresses with country names.
#   Use the geoip database to replace any non-rfc1918 address with its country name.
#


__autor__ = 'Are Hansen'
__date__ = '2014, October 10'
__version__ = 'DEV 0.0.1'


import sys

newlog = []
loglines = []


# Reads the lines from whatever file sys.argv[1] points to,
with open(sys.argv[1], 'r') as lines:
    for line in lines.readlines():
        # create a list object of each line and appends that list object to loglines.
        loglines.append(line.rstrip().split())

# Remove any NULL value indexes from the loglines list, creating the newlog list object. 
newlog = filter(None, loglines)

# Itterate over the newlog list object and extract the data thats used for building a 
# Lostalgic formatted log file.
for log in newlog:

    # Time stamp format
    date = '[{0}/{1}/2014:{2} +0200]'.format(log[1], log[0], log[2])

    # Check for certain tag words in the list indexes
    for tag in log:

        # Find what action was preformed.
        if 'ALLOW' in tag:
            # If the index contains the ALLOW string, set action = 2
            act = '2'

        if 'BLOCK' in tag:
            # If the index contains the BLOCK string, set action = 1
            act = '1'

        # Find the source and destination.
        if 'SRC=' in tag:
            src = tag.split('=')[1]

        if 'DST=' in tag:
            dst = tag.split('=')[1]

        # Find the protocol thats used.
        if 'PROTO=' in tag:
            prt = tag.split('=')[1]

        # Find the destination port.
        if 'DPT' in tag:
            dpt = tag.split('=')[1]

    # Construct the "access.log" like line using the data from the list indexes.
    print '{0} - - {1} "GET {3}{4} {2}" {5} {2}'.format(src, date, act, prt, dpt, dst)


"""
This is the command used by logstalgia when reading the log file:

logstalgia 1280x800 -f -x --glow-duration 0.9 --font-size 14 --hide-paddle \
--disable-progress -g " ,CODE=^2,49,00FF00" -g " ,CODE=^1,49,FF0000" -s 7 -u 1 LOGFILE
"""
